before_script:
  - ls
  - whoami
 
deploy_stage:
    stage: deploy
    environment: Staging
    script:
      - pwd
      - ls /var/www/climix-test/flaskapp/game_data
      - rm flaskapp/static/logo.png
      - mv flaskapp/static/logoTest.png flaskapp/static/logo.png
      - make deploiement_test
      - sudo /etc/init.d/apache2 restart

deploy_production:
  stage: deploy
  environment: Production
  only:
    - tags
  script:
      - pwd
      - ls /var/www/climix-test/flaskapp/game_data
      - rm flaskapp/static/logo.png
      - mv flaskapp/static/logoTest.png flaskapp/static/logo.png
      - make deploiement_stable
      - sudo /etc/init.d/apache2 restart

deploy_production:
  stage: pre
  environment: Staging
  script:
      - pwd
      - rm -rf /var/www/climix_test/venv
      - cd /var/www/climix_test && ./creer_venv.sh
      - make deploiement_stable
      - sudo /etc/init.d/apache2 restart

