before_script:
  - ls
  - whoami
  - pwd
 
deploy_stage:
    stage: deploy
    environment: Staging
    script:
      - ls /var/www/climix-test/flaskapp/game_data
      - rm flaskapp/static/logo.png
      - mv flaskapp/static/logoTest.png flaskapp/static/logo.png
      - make deploiement_test
      - sudo /etc/init.d/apache2 restart

deploy_production:
  stage: deploy
  environment: Production
  only:
    - tags
  script:
      - ls /var/www/climix/flaskapp/game_data
      - rm flaskapp/static/logo.png
      - mv flaskapp/static/logoStable.png flaskapp/static/logo.png
      - make deploiement_stable
      - sudo /etc/init.d/apache2 restart

deploy_public:
  stage: public
  environment: Production
  only:
    - public
  script:
      - ls /var/www/climix-public/flaskapp/game_data
      - rm flaskapp/static/logo.png
      - mv flaskapp/static/logoPublic.png flaskapp/static/logo.png
      - make deploiement_public
      - sudo /etc/init.d/apache2 restart
