before_script:
  - ls
  - whoami
 
deploy_stage:
    stage: deploy
    environment: Staging
    script:
      - pwd
      - ls /var/www/climix-test/flaskapp/game_data
      - rm flaskapp/static/logo.png
      - mv flaskapp/static/logoTest.png flaskapp/static/logo.png
      - make deploiement_test
      - sudo /etc/init.d/apache2 restart

deploy_production:
  stage: deploy
  environment: Production
  only:
    - tags
  script:
      - pwd
      - rm -rf .git/
      - rm flaskapp/app.wsgi
      - cp -r . /var/www/climix/
      - cd /var/www/climix/
      - source venv/bin/activate
      - ./deploiement.sh
      - sudo /etc/init.d/apache2 restart

