before_script:
  - ls
  - whoami
  - ls flaskapp
deploy_stage:
    stage: deploy
    environment: Staging
    script:
      - pwd
      - rm -rf .git/
      - rm flaskapp/static/logo.png
      - mv flaskapp/static/logoTest.png flaskapp/static/logo.png
      - rm -f flaskapp/constantes.py
      - cp -r . /var/www/climix-test/
      - ls /var/www/climix-test/flaskapp/
deploy_production:
  stage: deploy
  environment: Production
  only:
    - tags
  script:
      - pwd
      - rm -rf .git/
      - cp -r . /var/www/climix/

