before_script:
  - ls
  - whoami
deploy_stage:
    stage: deploy
    environment: Staging
    script:
      - pwd
      - rm -rf .git/
      - rm flaskapp/static/img/logo.png
      - mv flaskapp/static/img/logoTest.png flaskapp/static/img/logo.png
      - cp -r . /var/www/climix-test/

